const STATE_START = "STATE_SETUP";
const STATE_MATCH = "STATE_MATCH";
const STATE_GAME_OVER = "STATE_GAME_OVER";

module.exports.STATE_START = STATE_START;
module.exports.STATE_MATCH = STATE_MATCH;
module.exports.STATE_GAME_OVER = STATE_GAME_OVER;