const START_MATCH = "START_MATCH";
const PLAY_CARD = "PLAY_CARD";
const ACCEPT_PENALTIES = "ACCEPT_PENALTIES";
const SELECT_COLOR = "SELECT_COLOR";

module.exports.START_MATCH = START_MATCH;
module.exports.PLAY_CARD = PLAY_CARD;
module.exports.ACCEPT_PENALTIES = ACCEPT_PENALTIES;
module.exports.SELECT_COLOR = SELECT_COLOR;