// MATCH
export const START_MATCH = "START_MATCH";
export const GAME_OVER = "GAME_OVER";
export const SET_PLAYER_COUNT = "SET_PLAYER_COUNT";
export const CARD_PLAYED = "CARD_PLAYED";
export const PENALTIES_ACCEPTED = "PENALTIES_ACCEPTED";

// APP
export const SET_APP_STATE = "SET_APP_STATE";